version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: 
        - github.com/IndraSty/smart-doc-intelligence
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - noctx
    - bodyclose
    - exhaustive
    - gocritic
  settings:
    misspell:
      locale: US
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - godot
      - path: docs/
        linters:
          - all
      - path: internal/mocks/
        linters:
          - unused