package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"

	"github.com/IndraSty/smart-doc-intelligence/config"
	_ "github.com/IndraSty/smart-doc-intelligence/docs" // generated by swag
	"github.com/IndraSty/smart-doc-intelligence/internal/ai/gemini"
	deliveryhttp "github.com/IndraSty/smart-doc-intelligence/internal/delivery/http"
	"github.com/IndraSty/smart-doc-intelligence/internal/delivery/http/handler"
	"github.com/IndraSty/smart-doc-intelligence/internal/delivery/http/middleware"
	"github.com/IndraSty/smart-doc-intelligence/internal/repository/postgres"
	redisrepo "github.com/IndraSty/smart-doc-intelligence/internal/repository/redis"
	"github.com/IndraSty/smart-doc-intelligence/internal/usecase"
	"github.com/IndraSty/smart-doc-intelligence/pkg/database"
	"github.com/IndraSty/smart-doc-intelligence/pkg/embedding"
	"github.com/IndraSty/smart-doc-intelligence/pkg/logger"
	"github.com/IndraSty/smart-doc-intelligence/pkg/queue"
	"github.com/IndraSty/smart-doc-intelligence/pkg/storage"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title           Smart Document Intelligence API
// @version         1.0.0
// @description     Async document processing API with AI-powered extraction, classification, and semantic search.
// @description     Upload PDF, PNG, JPG, or TXT documents and get structured data extracted automatically.

// @contact.name    Indra Styawan
// @contact.url     https://github.com/IndraSty
// @contact.email   your-email@example.com

// @license.name    MIT
// @license.url     https://opensource.org/licenses/MIT

// @host            localhost:8080
// @BasePath        /

// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     JWT access token. Format: Bearer {token}

// @securityDefinitions.apikey ApiKeyAuth
// @in              header
// @name            X-API-Key
// @description     SHA-256 hashed API key obtained at registration

// @tag.name        auth
// @tag.description User registration and authentication

// @tag.name        documents
// @tag.description Document upload, retrieval, and management

// @tag.name        search
// @tag.description Semantic, full-text, and hybrid document search

// @tag.name        system
// @tag.description Health check and system status

func main() {
	// ── Bootstrap ────────────────────────────────────────────────────
	log := logger.New("development")
	log.Info().Msg("Starting Smart Document Intelligence API...")

	if err := run(log); err != nil {
		log.Fatal("Application error", err)
	}

}

func run(log *logger.Logger) error {
	// ── Config ───────────────────────────────────────────────────────
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	log = logger.New(cfg.App.Env)
	log = log.WithService("api")

	ctx := context.Background()

	// ── Migrations ───────────────────────────────────────────────────
	m, err := migrate.New("file://migrations", cfg.Database.URL)
	if err != nil {
		return fmt.Errorf("failed to initialize migrations: %w", err)
	}
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return fmt.Errorf("failed to run migrations: %w", err)
	}
	log.Info().Msg("Database migrations applied")

	// ── Database ─────────────────────────────────────────────────────
	pool, err := database.NewPostgresPool(ctx, &cfg.Database, log)
	if err != nil {
		return fmt.Errorf("failed to connect to PostgreSQL: %w", err)
	}
	defer pool.Close()

	// ── Redis ────────────────────────────────────────────────────────
	redisClient, err := redisrepo.NewRedisClient(cfg.Redis.URL, log)
	if err != nil {
		return fmt.Errorf("failed to connect to Redis: %w", err)
	}
	defer func() { _ = redisClient.Close() }()

	// ── RabbitMQ ─────────────────────────────────────────────────────
	queueClient, err := queue.NewClient(&cfg.RabbitMQ, log)
	if err != nil {
		return fmt.Errorf("failed to connect to RabbitMQ: %w", err)
	}
	defer queueClient.Close()

	// ── Storage ──────────────────────────────────────────────────────
	storageClient := storage.NewClient(&cfg.Supabase, log)

	// ── AI ───────────────────────────────────────────────────────────
	aiClient, err := gemini.NewClient(ctx, &cfg.Gemini, log)
	if err != nil {
		return fmt.Errorf("failed to initialize Gemini client: %w", err)
	}
	_ = aiClient

	embedder, err := embedding.NewGenerator(ctx, &cfg.Gemini, log)
	if err != nil {
		return fmt.Errorf("failed to initialize embedding generator: %w", err)
	}
	defer func() { _ = embedder.Close() }()

	// ── Repositories ─────────────────────────────────────────────────
	userRepo := postgres.NewUserRepository(pool, log)
	docRepo := postgres.NewDocumentRepository(pool, log)
	extractionRepo := postgres.NewExtractionRepository(pool, log)
	jobRepo := redisrepo.NewJobRepository(redisClient, log)

	// ── Usecases ─────────────────────────────────────────────────────
	processingUC := usecase.NewProcessingUsecase(jobRepo, docRepo, queueClient, log)
	userUC := usecase.NewUserUsecase(userRepo, cfg, log)
	documentUC := usecase.NewDocumentUsecase(docRepo, jobRepo, processingUC, storageClient, cfg, log)
	searchUC := usecase.NewSearchUsecase(extractionRepo, docRepo, embedder, log)

	// ── Middleware ───────────────────────────────────────────────────
	authMW := middleware.NewAuthMiddleware(userRepo, cfg, log)
	rateLimiter := middleware.NewRateLimiter(&cfg.RateLimit, log)

	// ── Handlers ─────────────────────────────────────────────────────
	authHandler := handler.NewAuthHandler(userUC, log)
	documentHandler := handler.NewDocumentHandler(documentUC, log)
	searchHandler := handler.NewSearchHandler(searchUC, log)
	healthHandler := handler.NewHealthHandler(pool, redisClient, queueClient, storageClient, log)

	// ── Router ───────────────────────────────────────────────────────
	router := deliveryhttp.NewRouter(deliveryhttp.RouterDeps{
		AuthHandler:     authHandler,
		DocumentHandler: documentHandler,
		SearchHandler:   searchHandler,
		HealthHandler:   healthHandler,
		AuthMiddleware:  authMW,
		RateLimiter:     rateLimiter,
		Config:          cfg,
		Log:             log,
	})
	router.GET("/swagger/*", echoSwagger.WrapHandler)

	// ── Server ───────────────────────────────────────────────────────
	port := cfg.App.Port
	if port == "" {
		port = "8080"
	}

	go func() {
		log.Info().Str("port", port).Msg("API server listening")
		if err := router.Start(":" + port); err != nil {
			log.Info().Msg("Server stopped")
		}
	}()

	// ── Graceful Shutdown ────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Info().Msg("Shutting down gracefully...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := router.Shutdown(shutdownCtx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Info().Msg("Server exited cleanly")
	return nil
}
